name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      run-tests:
        required: true
        type: boolean
    secrets:
      secret_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        if: ${{ inputs.run-tests }}
        run: pytest

      - name: Use Secret Token
        run: |
          echo "Using secret token: ${{ secrets.secret_token }}"
