name: Example Workflow with Multiple Contexts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: string
        default: 'staging'

jobs:
  # Job 1: Prepare
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"

  # Job 2: Build
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Print Job Context
        run: echo "Job status: ${{ job.status }}"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  # Job 3: Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print Runner Context
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"
          echo "Runner Temp Directory: ${{ runner.temp }}"

      - name: Use Secrets
        env:
          DEPLOY_PASSWORD: ${{ secrets.password }}
        run: |
          echo "Deploying with password: ${{ env.DEPLOY_PASSWORD }}"

      - name: Print Input
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"

      - name: Deploy application
        run: |
          echo "Deploying to ${{ github.ref }} on environment ${{ github.event.inputs.environment }}"
