name: "Démo: Priorité des Variables dans GitHub Actions"

on:
  push:
    branches:
      - main

jobs:
  test-priority:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Afficher la variable locale
        env:
          LOCAL_VAR: "Valeur locale dans le workflow"
        run: |
          echo "Valeur locale de LOCAL_VAR : $LOCAL_VAR"

      - name: Afficher la variable VAR_1 (environment, dépôt, organisation)
        run: |
          echo "Valeur de VAR_1 : ${{ vars.VAR_1 }}"  # Priorité à l'environnement

      - name: Afficher la variable VAR_2 (dépôt, organisation)
        run: |
          echo "Valeur de VAR_2 : ${{ vars.VAR_2 }}"  # Priorité au dépôt

      - name: Afficher la variable VAR_3 (organisation uniquement)
        run: |
          echo "Valeur de VAR_3 : ${{ vars.VAR_3 }}"  # Valeur de l'organisation
